# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pirobot2019.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pirobot2019.proto',
  package='pirobot2019',
  serialized_pb=_b('\n\x11pirobot2019.proto\x12\x0bpirobot2019\"H\n\x0bVelocityXYZ\x12\x0c\n\x01x\x18\x01 \x01(\x02:\x01\x30\x12\x0c\n\x01y\x18\x02 \x01(\x02:\x01\x30\x12\x0c\n\x01z\x18\x03 \x01(\x02:\x01\x30\x12\x0f\n\x04kick\x18\x04 \x01(\x02:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VELOCITYXYZ = _descriptor.Descriptor(
  name='VelocityXYZ',
  full_name='pirobot2019.VelocityXYZ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='pirobot2019.VelocityXYZ.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='pirobot2019.VelocityXYZ.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='pirobot2019.VelocityXYZ.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kick', full_name='pirobot2019.VelocityXYZ.kick', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['VelocityXYZ'] = _VELOCITYXYZ

VelocityXYZ = _reflection.GeneratedProtocolMessageType('VelocityXYZ', (_message.Message,), dict(
  DESCRIPTOR = _VELOCITYXYZ,
  __module__ = 'pirobot2019_pb2'
  # @@protoc_insertion_point(class_scope:pirobot2019.VelocityXYZ)
  ))
_sym_db.RegisterMessage(VelocityXYZ)


# @@protoc_insertion_point(module_scope)
